Update troubleshooting-modelling.csv
ValueError: Length mismatch: Expected axis has 1 elements, new values have 8760 elements Flow: ID_pv_to_ID_electricity_link-ID_pv_bus. This could be caused by NaN-values in your input data., The Model isn't solvable, because of wrong energybalance., Activate all excesses and shortages under buses.