Update 2_Urban_District_Upscaling.py
By using the original file, It wasn't possible to save a model definition created by the upscaling tool. The following error message was caused:

File "C:\Users\xxxxxx\program_files\GUI_st\pages\2_Urban_District_Upscaling.py", line 175, in us_application_start_download
    if os.path.exists(res_folder_path) is False:
NameError: name 'res_folder_path' is not defined

By reintegrating the code section in the comments, it was possible for me to save the file.

However, I am not sure why the code section was initially excluded and whether the change affects other functionalities.